# Generated by Django 5.1.6 on 2025-03-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
